### ISSUE TITLE
Can you provide instructions to compile with Windows?

### ISSUE THREAD

**Issue by furtabs** [water-works/mupen64plus-netplay#11]

**Comment by alexgolec** [comment]
No thanks, they came with my house.

**Comment by furtabs** [comment]
@alexgolec  dont be smart

**Comment by alexgolec** [comment]
Thanks for updating the title. 

Unfortunately we developed this entirely on Mac OS/Linux, so we have no ability to build on Windows. That being said, the reason we didn’t try was that we were having version incompatibility issues with GRPC and their overall build toolchain. It’s possible that the situation has improved since then.
